import type { Node, Edge } from "@xyflow/react"
import type { DiagramDefinition } from "./index"

const nodes: Node[] = [
  {
    id: "polecat-write",
    position: { x: 0, y: 80 },
    data: { label: "Polecat writes code" },
    style: {
      padding: "14px 22px",
      borderRadius: "8px",
      fontSize: "13px",
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 600,
      background: "rgba(59,130,246,0.1)",
      borderColor: "rgba(59,130,246,0.5)",
      border: "1px solid rgba(59,130,246,0.5)",
      color: "#3b82f6",
      minWidth: "160px",
      textAlign: "center" as const,
    },
  },
  {
    id: "push",
    position: { x: 230, y: 80 },
    data: { label: "Push branch" },
    style: {
      padding: "14px 22px",
      borderRadius: "8px",
      fontSize: "13px",
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 600,
      background: "rgba(255,255,255,0.03)",
      borderColor: "rgba(255,255,255,0.15)",
      border: "1px solid rgba(255,255,255,0.15)",
      color: "#ccc",
      minWidth: "120px",
      textAlign: "center" as const,
    },
  },
  {
    id: "refinery-review",
    position: { x: 420, y: 80 },
    data: { label: "Refinery reviews" },
    style: {
      padding: "14px 22px",
      borderRadius: "8px",
      fontSize: "13px",
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 600,
      background: "rgba(251,191,36,0.1)",
      borderColor: "rgba(251,191,36,0.5)",
      border: "1px solid rgba(251,191,36,0.5)",
      color: "#fbbf24",
      minWidth: "160px",
      textAlign: "center" as const,
    },
  },
  {
    id: "approve",
    position: { x: 620, y: 0 },
    data: { label: "✓ Approve & Merge" },
    style: {
      padding: "14px 22px",
      borderRadius: "8px",
      fontSize: "13px",
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 600,
      background: "rgba(34,197,94,0.1)",
      borderColor: "rgba(34,197,94,0.5)",
      border: "1px solid rgba(34,197,94,0.5)",
      color: "#22c55e",
      minWidth: "160px",
      textAlign: "center" as const,
    },
  },
  {
    id: "feedback",
    position: { x: 620, y: 160 },
    data: { label: "✗ Send feedback" },
    style: {
      padding: "14px 22px",
      borderRadius: "8px",
      fontSize: "13px",
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 600,
      background: "rgba(249,115,22,0.1)",
      borderColor: "rgba(249,115,22,0.5)",
      border: "1px solid rgba(249,115,22,0.5)",
      color: "#f97316",
      minWidth: "160px",
      textAlign: "center" as const,
    },
  },
  {
    id: "revise",
    position: { x: 230, y: 220 },
    data: { label: "Polecat revises" },
    style: {
      padding: "14px 22px",
      borderRadius: "8px",
      fontSize: "13px",
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 600,
      background: "rgba(59,130,246,0.1)",
      borderColor: "rgba(59,130,246,0.5)",
      border: "1px solid rgba(59,130,246,0.5)",
      color: "#3b82f6",
      minWidth: "160px",
      textAlign: "center" as const,
    },
  },
]

const edges: Edge[] = [
  {
    id: "write-push",
    source: "polecat-write",
    target: "push",
    animated: true,
    style: { strokeWidth: 2, stroke: "#3b82f6" },
  },
  {
    id: "push-review",
    source: "push",
    target: "refinery-review",
    animated: true,
    style: { strokeWidth: 2, stroke: "#fbbf24" },
  },
  {
    id: "review-approve",
    source: "refinery-review",
    target: "approve",
    animated: true,
    style: { strokeWidth: 2, stroke: "#22c55e" },
  },
  {
    id: "review-feedback",
    source: "refinery-review",
    target: "feedback",
    style: { strokeWidth: 2, stroke: "#f97316", strokeDasharray: "5 3" },
  },
  {
    id: "feedback-revise",
    source: "feedback",
    target: "revise",
    style: { strokeWidth: 2, stroke: "#f97316", strokeDasharray: "5 3" },
  },
  {
    id: "revise-review",
    source: "revise",
    target: "refinery-review",
    type: "smoothstep",
    animated: true,
    label: "re-submit",
    labelStyle: { fontSize: 10, fontFamily: "'JetBrains Mono', monospace", fill: "#888" },
    style: { strokeWidth: 2, stroke: "#3b82f6" },
  },
]

export const adversarialLoop: DiagramDefinition = {
  nodes,
  edges,
  caption: "The micro-adversarial loop — write, review, revise until quality is met",
}
