#!/usr/bin/env bun

/**
 * Extracts user-facing URLs from the VS Code extension and CLI source code,
 * then writes them to a markdown file that lychee can check for broken links.
 */

import { Glob } from "bun"
import path from "path"

const ROOT = path.resolve(import.meta.dir, "..")
const OUTPUT = path.join(ROOT, "source-links.md")

const DIRS = [
  path.join(ROOT, "packages/kilo-vscode/src"),
  path.join(ROOT, "packages/kilo-vscode/webview-ui"),
  path.join(ROOT, "packages/opencode/src"),
]

const EXTENSIONS = ["ts", "tsx", "js", "jsx"]

// Matches http:// and https:// URLs in string literals or comments
const URL_RE = /https?:\/\/[^\s"'`)\]},;*\\<>]+/g

// URLs to exclude — API endpoints, localhost, examples, dynamic templates, namespaces
const EXCLUDE_PATTERNS = [
  // Localhost and internal
  /^https?:\/\/(localhost|127\.0\.0\.1|0\.0\.0\.0)/,
  /^https?:\/\/kilo\.internal/,
  /^https?:\/\/tauri\.localhost/,
  // Example/placeholder URLs
  /^https?:\/\/example\.com/,
  /^https?:\/\/api\.myprovider\.com/,
  /^https?:\/\/synthetic\.new/,
  // API endpoints (not user-facing)
  /^https?:\/\/api\.kilo\.ai\/api\//,
  /^https?:\/\/ingest\.kilosessions\.ai/,
  /^https?:\/\/api\.openai\.com/,
  /^https?:\/\/api\.github\.com/,
  /^https?:\/\/api\.cloudflare\.com/,
  /^https?:\/\/api\.releases\.hashicorp\.com/,
  /^https?:\/\/auth\.openai\.com/,
  /^https?:\/\/chatgpt\.com\/backend-api/,
  /^https?:\/\/mcp\.exa\.ai/,
  /^https?:\/\/registry\.npmjs\.org/,
  /^https?:\/\/formulae\.brew\.sh\/api/,
  /^https?:\/\/community\.chocolatey\.org\/api/,
  /^https?:\/\/download-cdn\.jetbrains\.com/,
  /^https?:\/\/raw\.githubusercontent\.com/,
  // XML/SVG namespace URIs
  /^https?:\/\/www\.w3\.org\//,
  // URLs that are templates with interpolation (contain ${ after stripping)
  /\$\{/,
  // Schema/config JSON URLs
  /\.json$/,
  // Archive downloads (tarballs, zips — these are versioned and break often)
  /\.(tar\.gz|zip|tgz)$/,
  /\/archive\//,
  /\/releases\/download\//,
  /\/releases\/latest$/,
  // GitHub URLs — excluded because they cause HTTP/2 protocol errors on GH Actions
  /^https?:\/\/github\.com\//,
  // URLs ending in common non-page extensions
  /\.(png|jpg|jpeg|gif|svg|ico)$/,
  // Truncated/placeholder URLs (e.g., https://…) or bare protocols
  /^https?:\/\/[\W]*$/,
  // GHE example domains
  /^https?:\/\/company\.ghe\.com/,
  // Example/template session URLs with placeholders
  /\/s\/abc123$/,
  // Truncated URL paths (e.g., /s/ with no ID)
  /\/s\/$/,
]

// Directories to skip entirely
const SKIP_DIRS = ["node_modules", ".storybook", "stories", "test", "tests", "__tests__", "__mocks__"]

// Subdirectories containing vendored/third-party code
const SKIP_PATH_SEGMENTS = ["continuedev"]

function shouldExclude(url: string): boolean {
  return EXCLUDE_PATTERNS.some((re) => re.test(url))
}

function shouldSkipFile(filepath: string): boolean {
  const relative = path.relative(ROOT, filepath)
  const parts = relative.split(path.sep)
  if (parts.some((p) => SKIP_DIRS.includes(p))) return true
  if (SKIP_PATH_SEGMENTS.some((seg) => relative.includes(seg))) return true
  // Skip test files
  if (/\.test\.[jt]sx?$/.test(filepath)) return true
  if (/\.spec\.[jt]sx?$/.test(filepath)) return true
  // Skip story files
  if (/\.stories\.[jt]sx?$/.test(filepath)) return true
  // Skip i18n locale files (contain placeholder URLs)
  if (/\/i18n\//.test(filepath) && !filepath.endsWith("en.ts")) return true
  return false
}

function clean(url: string): string {
  // Remove trailing punctuation that's not part of the URL
  let cleaned = url.replace(/[.),:;]+$/, "")
  // Remove trailing HTML-like tags (e.g., </span>)
  cleaned = cleaned.replace(/<\/?\w+>$/, "")
  return cleaned
}

async function extract(): Promise<Map<string, Set<string>>> {
  const links = new Map<string, Set<string>>()

  for (const dir of DIRS) {
    for (const ext of EXTENSIONS) {
      const glob = new Glob(`**/*.${ext}`)
      for await (const entry of glob.scan({ cwd: dir, absolute: true })) {
        if (shouldSkipFile(entry)) continue
        const content = await Bun.file(entry).text()
        const lines = content.split("\n")
        for (const line of lines) {
          const matches = line.matchAll(URL_RE)
          for (const match of matches) {
            const url = clean(match[0])
            if (shouldExclude(url)) continue
            if (!links.has(url)) links.set(url, new Set())
            links.get(url)!.add(path.relative(ROOT, entry))
          }
        }
      }
    }
  }

  return links
}

const links = await extract()
const sorted = [...links.entries()].sort(([a], [b]) => a.localeCompare(b))

const parts = [
  "# Source Code Links",
  "",
  `<!-- Auto-generated by script/extract-source-links.ts — ${sorted.length} unique URLs -->`,
  "",
]

for (const [url, files] of sorted) {
  parts.push(`- <${url}>`)
  for (const file of [...files].sort()) {
    parts.push(`  <!-- ${file} -->`)
  }
}

parts.push("")

await Bun.write(OUTPUT, parts.join("\n"))
console.log(`Wrote ${sorted.length} unique URLs to ${OUTPUT}`)
